Initial updates
JaveLLC/jave pull request #1
Opened 2018-02-07 21:05 UTC by asciifaceman

2018-02-07 21:10 UTC, slavaaaaaaaaaa submitted a review, later dismissed

2018-02-07 21:10 UTC, smaslennikov commented on README.md
> +x is identical to 5
But I kind of like the -_- operator

2018-02-07 21:11 UTC, asciifaceman commented on README.md
> +x is identical to 5
I thought about it, but I want to avoid symbols as they are not conversational

2018-02-07 21:12 UTC, asciifaceman commented on README.md
> +x is identical to 5
I was going to go out of left field with like

x ∆ƒåå 5 type shit

2018-02-07 21:14 UTC, smaslennikov commented on README.md
> +  y is identical to 1
maybe this should be equal rather than identical

but who cares

2018-02-07 21:14 UTC, smaslennikov commented on README.md
> +  y is identical to 1
assignment vs comparison

2018-02-07 21:14 UTC, smaslennikov commented on README.md
> +  y is identical to 1
perfect score

2018-02-07 21:15 UTC, smaslennikov commented on README.md
>  during x being less than identical to the value of 10 engage
omg yes

2018-02-07 21:15 UTC, smaslennikov commented
how do i mega approve this

2018-02-07 21:35 UTC, slavaaaaaaaaaa requested changes

2018-02-07 21:35 UTC, smaslennikov commented on README.md
> +    Sonny.Moore which contains an array values consisting of 0 and 0 and 1
*of values

2018-02-07 21:54 UTC, slavaaaaaaaaaa approved these changes

2018-02-07 21:56 UTC, asciifaceman commented
I can't merge btw your perms are fecked

2018-02-08 15:37 UTC, merged

2018-02-08 15:38 UTC, smaslennikov commented
Your privs should be fixed now though.